# Generated by Django 2.1.2 on 2019-08-12 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Veicuo',
            new_name='Veiculo',
        ),
    ]
